### PR TITLE
[#419] Fix Purpose Restriction (narrowedVendors)

### LINKED ISSUE #419: TC string larger than 4096 bytes
**Version**
1.5.9
**Module (core, cmpapi, cli, stub, or testing)**
core
**Describe with reproduction steps – What is the expected behavior?**
TC string created using GVLv3 and version 1.5.9 of core lib is in our case 4642 bytes big. With the previous version it was much smaller. We are setting publisher restrictions REQUIRE_CONSENT for all purposes and vendors. In the previous version method restrictPurposeToLegalBasis of TCModel was setting the restrictions in another way. I attached the big TC string. 
We need a solution for this, since we need to store the TC string in the cookie.

[tcstring-GVLv3-core-1.5.9.txt](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/files/12598363/tcstring-GVLv3-core-1.5.9.txt)

### PR DESCRIPTION
**Pull request by marco-prontera**
The goal of this PR is to fix a bug caused in https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/407.

closes #419

The usage described in the issue wasn't covered by test.
So I implemented the test to cover this use case and fixed the code.
Notice that I leaved there the Set instead of BST since BST was the causes of performance issue.

### CODE REVIEW

**Comment by marco-prontera** [comment]
@sevriugin Basically it was an untested case, so any other change could cause this bug. Since I believe it is important to cover this use case I have implemented a specific test.

Let me know ;)

**Comment by jelenatomcic** [comment]
@marco-prontera When can we expect this bugfix release to be available?

**Comment by marco-prontera** [comment]
> @marco-prontera When can we expect this bugfix release to be available?

I'm a contributor, I don't have rights to merge or release a new version, sorry.
Maybe @sevriugin can help you

**Comment by jelenatomcic** [comment]
@sevriugin Is there news about this bugfix release, when will it be available?

**Comment by sevriugin** [comment]
@jelenatomcic merged, thanks

**Comment by jelenatomcic** [comment]
@sevriugin Will there be a new bugfix release? Like 1.5.10?

**Pull request merged**
