### PR TITLE
adding language support for HE, ID, KO, MK, MS, TL

### PR DESCRIPTION
**Pull request by HeinzBaumann**
Added support for the following languages:
Indonesian: id
Korean: ko
Malay: ms
Tagalog: tl
Hebrew: he
Macedonian: mk
Passes tests and successfully builds.

### CODE REVIEW

**Comment by sevriugin** [comment]
LGTM

**Comment by janwinkler** [comment]
How/why is this needed if the texts are not supplied by the IAB?
https://register.consensu.org/Translation

**Comment by uc-leo** [comment]
hello @HeinzBaumann 

do you know when will they be in the [official purposes translations list](https://register.consensu.org/Translation)?

thanks

**Comment by HeinzBaumann** [comment]
@uc-leo @janwinkler This is work in progress at IAB EU. These additional languages will be published within the next week or two.

**Review by lamrowena — APPROVED** [review]

**Pull request merged**
