### PR TITLE
Addresses #147 inconpatability between nodejs and browser base64 

### PR DESCRIPTION
**Pull request by chrispaterson**
re-writes base64url class

### CODE REVIEW

**Comment by vincent-ogury** [comment]
Hi,
on nodejs, I have an hack to set global atob and btoa to make the 1.0.0 works. Or I've got bad encoding.

when do you think you will be able to merge and release this patch ?

**Comment by chrispaterson** [comment]
@vincent-ogury I'll release this as a release candidate 1.0.1-0.  Feedback would be appreciated!

**Comment by chrispaterson** [comment]
It is published as 1.0.1-0 now

**Comment by vincent-ogury** [comment]
Tested. The encode/decode works now! It is compatible with http://iabtcf.com/#/decode

**Pull request merged**
