### PR TITLE
Device Storage Disclosure fields for Vendor model

### PR DESCRIPTION
**Pull request by shortaflip**
**Added the following fields to the Vendor model:**
* cookieMaxAgeSeconds
* usesNonCookieAccess
* deviceStorageDisclosureUrl

### CODE REVIEW

**Comment by nejcsever** [comment]
FYI, this also solves #237. It's a shame that this project has stalled and no pull requests are merged.

**Comment by shortaflip** [comment]
> FYI, this also solves #237. It's a shame that this project has stalled and no pull requests are merged.

Oh, thank you very much, I'll link the issue.

**Comment by brianxieseattle** [comment]
Is there any chance this can be merged?

**Comment by alextcone** [comment]
This looks good to merge to me. I'm not assigned as a reviewer, but I give it a thumbs up.

**Review by alextcone — APPROVED** [review]

**Review by HeinzBaumann — APPROVED** [review]

**Comment by dmdabbs** [comment]
Thanks @HeinzBaumann !

**Pull request merged**
