### PR TITLE
[#406] Improve library performance when creating publisher restrictions

### LINKED ISSUE #406: Improve library performance when creating publisher restrictions for vendors ids above 4000
It looks like the core library is slow when working with GVL where vendors ids are above 4000. For the lates GVL update ([v208](https://vendor-list.consensu.org/v2/vendor-list.json)) where we have vendor "Advertising.Tech FZ-LLC" added with id 4176 we have experienced significant delays for TCString encoding / decoding. 

For example this short string:

`CPv0u4APv0u4AAHABBENDQCsAP_AAAAAAAAAJNFT_T_cT3NjeX5_7vt0eY1ew1y-r-giDgKZA6wJSXqAsJwH0mAqKF3AgqgKgB4EIHbBAQBlHAHAREEgQIEBATGMAEWQJRIIIqLAEAIRAgIACAlZHYEQGAIQgPQACDQIkAOGCHsoUOFFOQAgDEAAIAqlAITFAgQYRBCAwIgIDAAIQi4BCAQAayAETEAAAFEIEABZAAEAAABISADAAEQUA0AGAAIgoCIAMAARBQFQAYAAiCgMgAwABEFAdABgACIKBCADAAEQUCUAGAAIgoFIAMAARBQA.f_gAAAAAAAAA` 

takes some time to decode in https://iabtcf.com/?#/decode

It looks like the issue is [here](https://github.com/didomi/iabtcf-es/blob/6ef07a0e6ddc48fe268d629c2c4a1ad457560aca/modules/core/src/encoder/field/PurposeRestrictionVectorEncoder.ts#L18) when we are calling `nextGvlVendor` for each publisher restrictions and for each vendor, as result `encode` takes around 370ms

### PR DESCRIPTION
**Pull request by marco-prontera**
closes #406 

The goal of this PR is to improve the performance for encoding and decoding a String when using the Purposes Restrictions. There is no need to say that this is important since  this impact to everything (at least everything that depend on a consent) in a website.

I tried also with the new vendorList v3 - version 11 https://vendor-list.consensu.org/v3/vendor-list.json and these are the performances before the changes I propose:
ENCODING (before)
pre-encode
DECODING (before)
pre-decode

After the changes I propose in this PR the performances are the following:
ENCODING (after changes)
post-encode
DECODING (after changes)
post-decode

### CODE REVIEW

**Comment by marco-prontera** [comment]
Hi @sevriugin, can you review this and also #409, #404 and #403 please?

**Comment by sevriugin** [comment]
In general LGTM, I have doubts regarding Array.from it could be an issue if some publisher is still using IE11

**Comment by marco-prontera** [comment]
> In general LGTM, I have doubts regarding Array.from it could be an issue if some publisher is still using IE11

@sevriugin Thank you for the review, `Array.from` is already used in this library also in the Core, so we can be sure that the usage is safe (also because IE11 reached the EOL)

**Comment by EdgardoRodriguezSolano** [comment]
Hello @aitnitishshelage Following yesterday's release, are there any plans to merge this one?

**Pull request merged**
