### PR TITLE
Use custom "getTCData" command handler for "addEventListener" and "removeEventListener" commands

### PR DESCRIPTION
**Pull request by kemalmustafic**
Closes https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/227 and https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/229

### CODE REVIEW

**Comment by jawadst** [comment]
@kemalmustafic Is there a way to add a test to confirm that it works as expected and that it doesn't break again in the future?

**Comment by kemalmustafic** [comment]
@jawadst Sure, I pushed a test to make sure that the custom `getTCData` command handler is called for `addEventListener` and `removeEventListener` commands

**Comment by alextcone** [comment]
@kemalmustafic & @jawadst - is this waiting to be merged?

**Comment by kemalmustafic** [comment]
@alextcone Yes, we are currently using our own fork of the library because of this fix.

Would be great if it could be merged and released in one of the upcoming releases so we could go back to the official library

**Comment by sklae** [comment]
Hi @kemalmustafic. Any news about the merge date?

**Comment by kemalmustafic** [comment]
Hello @sklae, we haven't received any update from the IAB regarding the merge date

**Comment by sklae** [comment]
@alextcone : Is there anyhow a chance to get this PR merged into the master soon?
The bug is out there since October last year. What's the reason for not merging it?
Thank you for your information.

**Comment by alextcone** [comment]
@sklae - There is one person in industry who had stepped up to manage this open source library. He moved on to another, not related to privacy at all role and thus we find ourselves until recently without volunteers to manage PRs and deploys in this library. @shortaflip has recently raised his hand to pitch in. Last week I shared write access with him and I believe he's getting to know the process.

This is understandably frustrating. It's our fault at Tech Lab for not building a bigger bench of open source contributors, but we're at least headed back in that direction with @shortaflip's volunteering. @sklae, if you would reach out to me directly at alex.cone at iabtechlab dot com we can talk about you joining in the volunteers that manage PRs, merges and versioning.

**Comment by sklae** [comment]
Thank you very much @alextcone for the detailed explanation to understand why the merges are delayed!
Reading that @shortaflip has volunteered and merging will be possible in the closer future is also great news.

Currently I'm not able to take on additional tasks but will keep your offer in mind. Thx a lot!

**Comment by opencmp** [comment]
When will this be released? I just tried the latest @iabtcf/cmpapi and @iabtcf/core and addEventListener is still not calling getTCData.
@shortaflip We appreciate if you could provide us with an estimate.

**Comment by shortaflip** [comment]
Hello @opencmp,

There is currently deliberation as to whether issue 261 and its corresponding pull request 262 should be included in the v1.2.1 release.  (The release that contains these changes) If I get direction from the IAB this week that issue 261 requires more talk and should be added in a future release, then v1.2.1 will be released next week.

**Pull request merged**
