### PR TITLE
Clone GVL without JSON.parse / JSON.stringify

### PR DESCRIPTION
**Pull request by sevriugin**
We need to avoid using `JSON.parse / JSON.stringify` when we clone very large object as it's very time consuming

### CODE REVIEW

**Review by patmmccann — APPROVED** [review]

**Comment by patmmccann** [comment]
As an aside, we've recently experimented with klona library with promising results on a different project

**Comment by sevriugin** [comment]
@patmmccann should we merge this one ?

**Comment by HeinzBaumann** [comment]
> @patmmccann should we merge this one ?

changes look good to me. I am okay with merging.

**Comment by honzalo** [comment]
Could this changes be merged?

**Comment by sevriugin** [comment]
I have rights to merge it, so we we don't have any objections then I can do it

**Pull request merged**
